/*
 * content.js — 导航单一真相源 (single source of truth)
 * 驱动：左侧 TOC 树、上下页导航、封面目录、客户端搜索。
 * 每个 section: { id, title, file, keywords }
 * file 路径相对于 learn/ 根目录。
 */
window.VBOOK = {
  title: "TinyVBD",
  subtitle: "从 PBD 到 Vertex Block Descent · 一本娓娓道来的交互式教程",
  parts: [
    {
      id: "p0",
      label: "Part 0",
      title: "序章 · Orientation",
      sections: [
        { id: "0-1", title: "这本书要带你去哪", file: "chapters/00-orientation/0-1-where-we-go.html",
          keywords: "vbd vertex block descent tinyvbd 序章 一句话 strand 头发 弹簧 mass spring 受众 怎么读" },
        { id: "0-2", title: "代码地图：7 个文件，一次 simulate()", file: "chapters/00-orientation/0-2-code-map.html",
          keywords: "code map 文件 main.cpp Strand.h Types.h json eigen simulate 全景 调用链 architecture" },
        { id: "0-3", title: "怎么读这本书 · 两座桥", file: "chapters/00-orientation/0-3-how-to-read.html",
          keywords: "how to read bridge games103 pbd 桥 受众 阅读指南 术语 中英文" },
      ],
    },
    {
      id: "p1",
      label: "Part 1",
      title: "数学地基 · The Variational View",
      sections: [
        { id: "1-1", title: "F=ma 与时间积分：explicit vs implicit Euler", file: "chapters/01-foundations/1-1-time-integration.html",
          keywords: "newton f=ma time integration explicit implicit euler 显式 隐式 欧拉 稳定 stability 爆炸 时间步 games103" },
        { id: "1-2", title: "隐式欧拉的变分真身：一步 = 最小化 G(x)", file: "chapters/01-foundations/1-2-variational-euler.html",
          keywords: "variational implicit euler incremental potential 最小化 optimization minimization argmin G(x) 变分 优化 数学本质 liu martin" },
        { id: "1-3", title: "质量矩阵 M：仿真里的质量长什么样", file: "chapters/01-foundations/1-3-mass-matrix.html",
          keywords: "mass matrix 质量矩阵 M 对角 diagonal lumped mass 集中质量 M-norm M范数 动能 kinetic energy m/h^2 正定 pinned 钉住 顶点质量" },
        { id: "1-4", title: "惯性项 y 与弹性能：一场拔河", file: "chapters/01-foundations/1-4-inertia-elastic.html",
          keywords: "inertia 惯性 y 预测位置 inertial position 弹性能 elastic energy 拔河 tug of war 质量 mass dt 时间步" },
        { id: "1-5", title: "弹簧的能量、力与 Hessian", file: "chapters/01-foundations/1-5-spring-energy.html",
          keywords: "spring energy force hessian 弹簧 能量 力 二阶导 gradient 梯度 stiffness 刚度 rest length 弹簧质点 正定 positive definite 碗 鞍点" },
      ],
    },
    {
      id: "p2",
      label: "Part 2",
      title: "三种解法的谱系 · The Family Tree",
      sections: [
        { id: "2-1", title: "PBD：粗暴调位置的真相，与它的病", file: "chapters/02-family/2-1-pbd.html",
          keywords: "pbd position based dynamics 粗暴 调位置 constraint projection gauss seidel 迭代 stiffness 依赖 病 weakness muller 2007" },
        { id: "2-2", title: "XPBD：用 compliance 和 λ 治病", file: "chapters/02-family/2-2-xpbd.html",
          keywords: "xpbd compliance alpha lagrange multiplier lambda 柔度 治病 implicit euler macklin 2016 时间步无关" },
        { id: "2-3", title: "Projective Dynamics：local/global", file: "chapters/02-family/2-3-projective-dynamics.html",
          keywords: "projective dynamics pd local global prefactorized cholesky 全局解 投影 bouaziz 2014 liu 2013 constraint" },
        { id: "2-4", title: "谱系图：都在解同一个 min G(x)", file: "chapters/02-family/2-4-family-tree.html",
          keywords: "family tree 谱系 对比 pbd xpbd pd vbd newton gauss seidel jacobi 解法 区别 统一" },
      ],
    },
    {
      id: "p3",
      label: "Part 3",
      title: "VBD 核心思想 · Vertex Block Descent",
      sections: [
        { id: "3-1", title: "Block coordinate descent：一次只动一个顶点", file: "chapters/03-vbd/3-1-block-descent.html",
          keywords: "block coordinate descent 坐标下降 一个顶点 vertex 局部 local 3x3 块 gauss seidel sweep" },
        { id: "3-2", title: "为什么局部下降 = 全局下降", file: "chapters/03-vbd/3-2-local-global-descent.html",
          keywords: "local global descent reduction 论证 monotone energy 能量单调 收敛 convergence 证明 G_i" },
        { id: "3-3", title: "每个顶点的 3×3 牛顿步：f_i 与 H_i", file: "chapters/03-vbd/3-3-newton-step.html",
          keywords: "newton step 3x3 f_i h_i force hessian gradient 牛顿 顶点力 顶点hessian 装配 assemble adjacent" },
        { id: "3-4", title: "Gauss-Seidel、Jacobi 与 graph coloring", file: "chapters/03-vbd/3-4-coloring-parallel.html",
          keywords: "gauss seidel jacobi graph coloring 图着色 并行 parallel gpu 顶点着色 vertex color 少颜色" },
        { id: "3-5", title: "不强制 SPD：稳定性从哪来", file: "chapters/03-vbd/3-5-stability.html",
          keywords: "spd positive definite 正定 稳定性 stability 惯性项 det 阈值 skip line search 不需要 robust" },
      ],
    },
    {
      id: "p4",
      label: "Part 4",
      title: "读 TinyVBD 的代码 · Code Walkthrough",
      sections: [
        { id: "4-1", title: "数据结构：Types.h 与 Strand.h", file: "chapters/04-code/4-1-data-structures.html",
          keywords: "types.h strand.h 数据结构 eigen edges vertAdjacentEdges skip spring orgLengths mVertPos mass from" },
        { id: "4-2", title: "forwardStep()：惯性与自适应初始化", file: "chapters/04-code/4-2-forward-step.html",
          keywords: "forwardstep 惯性 inertia 自适应初始化 adaptive initialization warm start accelerationComponent gravity 预测" },
        { id: "4-3", title: "solve()：一次 Gauss-Seidel sweep 逐行解剖", file: "chapters/04-code/4-3-solve.html",
          keywords: "solve gauss seidel sweep 逐行 dissect f h hessian 弹簧 stiffness colPivHouseholderQr dx 顶点更新" },
        { id: "4-4", title: "Chebyshev 加速：omega 与 applyAccelerator", file: "chapters/04-code/4-4-chebyshev.html",
          keywords: "chebyshev acceleration omega rho getAcceleratorOmega applyAccelerator prevprevPos 加速 收敛 spectral radius" },
        { id: "4-5", title: "simulate() 主循环与可视化", file: "chapters/04-code/4-5-main-loop.html",
          keywords: "simulate main loop substep frame iteration updateVelocity saveOutputs json blender 可视化 主循环" },
      ],
    },
    {
      id: "p5",
      label: "Part 5",
      title: "实验与压力测试 · Experiments",
      sections: [
        { id: "5-1", title: "高质量比：XPBD 为何崩、VBD 为何不崩", file: "chapters/05-experiments/5-1-mass-ratio.html",
          keywords: "high mass ratio 高质量比 1000 heavy tip 崩 crush primal dual xpbd vbd 不崩 initializeTilted 实验" },
        { id: "5-2", title: "高刚度比：VBD 的软肋", file: "chapters/05-experiments/5-2-stiffness-ratio.html",
          keywords: "stiffness ratio 刚度比 软肋 limitation 1e4 1e8 收敛慢 initializeStiffRatio 局部方法 local 信息传播" },
        { id: "5-3", title: "skip spring = 弯曲，与迭代数的影响", file: "chapters/05-experiments/5-3-skip-spring-iterations.html",
          keywords: "skip spring 弯曲 bending i i+2 迭代数 numIterations 收敛 收敛速度 substep 实验菜单" },
        { id: "5-4", title: "你能跑的实验菜单", file: "chapters/05-experiments/5-4-experiment-menu.html",
          keywords: "experiment menu 实验菜单 config 配置 注释 uncomment initializeHorizontal initializeTilted converged 玩法" },
      ],
    },
    {
      id: "p6",
      label: "Part 6",
      title: "收尾 · The Bigger Picture",
      sections: [
        { id: "6-1", title: "VBD 在谱系里的位置、局限与 AVBD", file: "chapters/06-closing/6-1-place-and-limits.html",
          keywords: "place limits avbd augmented vertex block descent 局限 stiffness ratio 硬约束 future 总结 谱系 位置" },
      ],
    },
    {
      id: "p7",
      label: "Part 7",
      title: "Newton 的世界 · Foundations (Warp + Newton)",
      sections: [
        { id: "7-1", title: "Newton 是什么：从 Isaac/USD 到 Warp-native 引擎", file: "chapters/07-newton-foundations/7-1-what-is-newton.html",
          keywords: "newton warp isaac usd physx mujoco warp.sim deprecated linux foundation gpu 引擎 robotics 定位 关系 disney deepmind nvidia" },
        { id: "7-2", title: "Warp 编程模型：kernel / array / launch / tid", file: "chapters/07-newton-foundations/7-2-warp-model.html",
          keywords: "warp wp.kernel wp.func wp.array wp.launch wp.tid spmd 线程 gpu vec3 mat33 cuda graph capture jit 编程模型" },
        { id: "7-3", title: "Newton 数据模型：Model / State / Control / Contacts", file: "chapters/07-newton-foundations/7-3-data-model.html",
          keywords: "model state control contacts modelbuilder particle_q particle_qd step 契约 静态 动态 数据模型 finalize" },
        { id: "7-4", title: "一个最小 Newton 程序：builder → color → step", file: "chapters/07-newton-foundations/7-4-minimal-program.html",
          keywords: "minimal program builder color finalize state control contacts step loop collide 最小程序 主循环 example" },
      ],
    },
    {
      id: "p8",
      label: "Part 8",
      title: "从一根 strand 到一块 cloth · TinyVBD → Newton particle VBD",
      sections: [
        { id: "8-1", title: "同一个 min G(x)，搬上 GPU：什么没变、什么变了", file: "chapters/08-strand-to-cloth/8-1-same-min-G.html",
          keywords: "min G(x) gpu strand cloth 没变 变了 主线 桥 tinyvbd 串行 并行 incremental potential 一样" },
        { id: "8-2", title: "SolverVBD 全景：step() 的三段式", file: "chapters/08-strand-to-cloth/8-2-solver-overview.html",
          keywords: "solvervbd step initialize iterate finalize 三段式 全景 substep iteration 结构 particle" },
        { id: "8-3", title: "particle 的惯性初始化（对照 TinyVBD 自适应初始化）", file: "chapters/08-strand-to-cloth/8-3-initialization.html",
          keywords: "forward_step 惯性 初始化 inertia y predicted position 自适应 adaptive 差异 对照 没有 acceleration component" },
        { id: "8-4", title: "per-vertex Newton step 在 Warp 里：f_i 与 H_i 装配", file: "chapters/08-strand-to-cloth/8-4-newton-step-warp.html",
          keywords: "per vertex newton step f_i h_i hessian 3x3 solve_elasticity kernel 装配 assemble mass dt 惯性项 inverse delta x" },
        { id: "8-5", title: "graph coloring 与并行 sweep", file: "chapters/08-strand-to-cloth/8-5-coloring-parallel.html",
          keywords: "graph coloring 顶点着色 primal dual 颜色 parallel sweep gauss seidel jacobi 并行 串行 对照 color groups" },
      ],
    },
    {
      id: "p9",
      label: "Part 9",
      title: "连续介质弹性的地基 · FEM",
      sections: [
        { id: "9-1", title: "为什么需要 FEM：从弹簧到连续介质", file: "chapters/09-fem/9-1-why-fem.html",
          keywords: "fem finite element 有限元 连续介质 continuum 弹簧 spring 推广 弹性能 strain energy 自由度 剪切 面积 体积 各向异性 min G(x)" },
        { id: "9-2", title: "形变梯度 F：把 rest 映到 world", file: "chapters/09-fem/9-2-deformation-gradient.html",
          keywords: "deformation gradient 形变梯度 F rest world 仿射 shape function constant strain 极分解 polar decomposition R S 旋转 拉伸 J det 翻转 inversion 单元 element" },
        { id: "9-3", title: "应变能密度 ψ(F) 与超弹性模型谱", file: "chapters/09-fem/9-3-strain-energy.html",
          keywords: "strain energy density 应变能 psi hyperelastic 超弹性 stvk co-rotational neo-hookean 不变量 invariant 压缩反转 smith 2018 lame mu lambda" },
        { id: "9-4", title: "Piola 应力 P=∂ψ/∂F 与单元力 / Hessian 装配", file: "chapters/09-fem/9-4-piola-assembly.html",
          keywords: "first piola kirchhoff stress 应力 P 单元力 element force hessian 装配 assembly spd projection 投影 fi hi 节点 node Dm" },
        { id: "9-5", title: "手把手算一遍：一个单元从 F 到 Δx", file: "chapters/09-fem/9-5-worked-tet.html",
          keywords: "worked example 算例 手把手 三角形 四面体 triangle tet F J 不变量 psi P 节点力 delta x 数字 复算 自洽示例" },
        { id: "9-6", title: "FEM 就是 min G(x) 的弹性项", file: "chapters/09-fem/9-6-fem-is-minG.html",
          keywords: "fem min G(x) 弹性项 incremental potential vbd newton 装配口 求和 单元能量 应用 10-1 neo-hookean 接口 参考文献" },
      ],
    },
    {
      id: "p10",
      label: "Part 10",
      title: "真实的弹性与碰撞 · Real Elasticity & Collisions",
      sections: [
        { id: "10-1", title: "弹性元件谱：membrane / volumetric / bending / spring", file: "chapters/10-elasticity-collision/10-1-elastic-elements.html",
          keywords: "neo hookean membrane volumetric tet bending dihedral spring 弹性 元件 cloth soft 三角 fem 能量 对照 弹簧 hessian" },
        { id: "10-2", title: "SPD 投影与 Rayleigh damping：production 稳定性", file: "chapters/10-elasticity-collision/10-2-spd-damping.html",
          keywords: "spd 投影 projection rayleigh damping kd ke stable neo hookean lambda mu clamp 稳定性 production 阻尼" },
        { id: "10-3", title: "self-collision 与 penetration-free", file: "chapters/10-elasticity-collision/10-3-collision.html",
          keywords: "self collision bvh penetration free truncation dat vertex triangle edge edge 碰撞 穿透 截断 对照 无碰撞" },
      ],
    },
    {
      id: "p11",
      label: "Part 11",
      title: "AVBD 与 rigid · 收尾概览",
      sections: [
        { id: "11-1", title: "VBD 的软肋 → AVBD：augmented Lagrangian 与 penalty ramping", file: "chapters/11-avbd/11-1-avbd-idea.html",
          keywords: "avbd augmented vertex block descent lagrangian penalty ramping k_start beta gamma warm start hard soft 软肋 高刚度比 giles 2025" },
        { id: "11-2", title: "Newton 里的 rigid AVBD 一瞥，与进一步阅读", file: "chapters/11-avbd/11-2-rigid-and-further.html",
          keywords: "rigid avbd joints contacts newton 限制 软约束 进一步阅读 further reading 论文 docs demo 收尾 总结" },
      ],
    },
    {
      id: "p12",
      label: "Part 12",
      title: "接触的第三条路 · IPC",
      sections: [
        { id: "12-1", title: "为什么还要 IPC：penalty / AVBD 之外的第三条路", file: "chapters/12-ipc/12-1-why-ipc.html",
          keywords: "ipc incremental potential contact 第三条路 penalty avbd intersection free 无穿透 接触三难 interior point barrier li 2020 动机" },
        { id: "12-2", title: "log-barrier 接触能量与解析式逐因子拆解", file: "chapters/12-ipc/12-2-barrier-energy.html",
          keywords: "log barrier 接触能量 interior point d hat 激活阈值 发散 解析式 公式 拆解 ln 对数 c2 光滑 distance min G(x) 对照 9-3 全局" },
        { id: "12-3", title: "距离几何：point-triangle / edge-edge 与梯度 ∂d/∂x", file: "chapters/12-ipc/12-3-distance-geometry.html",
          keywords: "distance 距离 point triangle edge edge 无符号 unsigned 最近点 closest barycentric 重心坐标 梯度 gradient 法向 退化 平行 mollifier 几何" },
        { id: "12-4", title: "barrier 求导与 PSD 投影：怎么进 Newton", file: "chapters/12-ipc/12-4-barrier-grad-psd.html",
          keywords: "链式法则 chain rule 梯度 gradient hessian 力 force psd projection spd 投影 半正定 特征值 下降方向 9-2 d hat 条件数" },
        { id: "12-5", title: "intersection-free 的真正来源：CCD-filtered line search", file: "chapters/12-ipc/12-5-ccd-linesearch.html",
          keywords: "ccd continuous collision detection line search 线搜索 最大安全步长 time of impact cfl 保守界 feasible 可行域 intersection free 对照 dat 9-3" },
        { id: "12-6", title: "摩擦：lagged、光滑化的 Coulomb", file: "chapters/12-ipc/12-6-friction.html",
          keywords: "friction 摩擦 coulomb lagged potential alternating 光滑化 mollified 可微 静摩擦 动摩擦 过渡 epsilon v smoothed" },
        { id: "12-7", title: "手把手算一遍：一个接触对从距离到 Δx", file: "chapters/12-ipc/12-7-worked-example.html",
          keywords: "worked example 算例 手把手 数字 point segment 距离 barrier 力 hessian psd delta x 具体 走读 复算 自洽示例" },
        { id: "12-8", title: "IPC 一次完整迭代：伪代码逐段走读", file: "chapters/12-ipc/12-8-ipc-iteration.html",
          keywords: "iteration 外迭代 伪代码 pseudocode 走读 assemble 装配 psd solve 方向 ccd line search accept 收敛 判据 流水线 仿 4-3" },
        { id: "12-9", title: "求解器全景与代价：为什么 IPC 稳但贵", file: "chapters/12-ipc/12-9-solver-cost.html",
          keywords: "solver 全局 newton sparse cholmod cholesky psd projection 装配 代价 cost 贵 ccd 全局解 condition number vbd 局部 对照 amgcl" },
        { id: "12-10", title: "ABD：把 IPC 用在近刚体上", file: "chapters/12-ipc/12-10-abd.html",
          keywords: "abd affine body dynamics 仿射体 近刚体 stiff 刚体 紧凑坐标 12 自由度 dof 仿射 orthogonality 正交能量 ipc intersection-free 继承 lan 2022 刚柔光谱 fem 对照" },
        { id: "12-11", title: "三条路总对照：penalty / AVBD / IPC", file: "chapters/12-ipc/12-11-three-roads.html",
          keywords: "对照表 penalty avbd ipc 三条路 保证 代价 可微 收敛 落地 何时选谁 银弹 总结 接触 收尾" },
      ],
    },
    {
      id: "p13",
      label: "Part 13",
      title: "物质点法 · MPM（含 MPM Lite 前沿）",
      sections: [
        { id: "13-1", title: "为什么 MPM：Lagrangian / Eulerian / hybrid", file: "chapters/13-mpm/13-1-why-mpm.html",
          keywords: "mpm material point method 物质点 lagrangian eulerian hybrid 混合 巨形变 断裂 fracture 沙 雪 流体 拓扑 mesh 撕裂 边界 sulsky" },
        { id: "13-2", title: "MPM 一步循环：粒子 ↔ 背景网格", file: "chapters/13-mpm/13-2-mpm-cycle.html",
          keywords: "mpm cycle 循环 p2g g2p particle grid 背景网格 transfer scratch advect 散布 插值 质量 动量 物质点" },
        { id: "13-3", title: "传输与 APIC：PIC 耗散、FLIP 噪声、APIC 修复", file: "chapters/13-mpm/13-3-transfers-apic.html",
          keywords: "transfer pic flip apic 传输 耗散 噪声 角动量 affine jiang 2015 mls-mpm hu 2018 moving least squares 仿射" },
        { id: "13-4", title: "粒子上的形变梯度更新 F←(I+∇v·dt)F + 本构", file: "chapters/13-mpm/13-4-F-update-constitutive.html",
          keywords: "deformation gradient update 形变梯度 更新 F nabla v 本构 constitutive psi piola 复用 fem 9-2 9-3 速度梯度" },
        { id: "13-5", title: "显式 vs 隐式 MPM：隐式 = 网格上的 min G(x)", file: "chapters/13-mpm/13-5-implicit-mpm.html",
          keywords: "explicit implicit mpm 显式 隐式 min G(x) 网格 grid dof 优化 newton 大步长 稳定 incremental potential 变分" },
        { id: "13-6", title: "MPM Lite 主讲：线性核、无粒子求积", file: "chapters/13-mpm/13-6-mpm-lite.html",
          keywords: "mpm lite linear kernel 线性核 quadrature 求积 particle 载体 kinematic implicit 加速 ppc stencil 手算 伪代码 mpmlite" },
        { id: "13-7", title: "PB-MPM：position-based，接回 PBD 家族", file: "chapters/13-mpm/13-7-pb-mpm.html",
          keywords: "pb-mpm position based mpm pbd xpbd 约束求解 大步长 稳定 ea seed siggraph 2024 chris lewin 游戏 物理 接回 part 2" },
        { id: "13-8", title: "CK-MPM：compact kernel 紧支撑核", file: "chapters/13-mpm/13-8-ck-mpm.html",
          keywords: "ck-mpm compact kernel 紧支撑 c2 连续 apic mls 网格节点 taichi gpu arxiv 2412.10399 b-spline 对照" },
        { id: "13-9", title: "MPM 篇收尾：三条现代路线与全书关系", file: "chapters/13-mpm/13-9-closing.html",
          keywords: "收尾 对照 mpm lite pb-mpm ck-mpm fem vbd ipc 关系 离散 dof 接触 参考文献 总结" },
      ],
    },
    {
      id: "pa",
      label: "Appendix",
      title: "附录 · Reference",
      sections: [
        { id: "a-1", title: "术语表 Glossary", file: "chapters/appendix/a-1-glossary.html",
          keywords: "glossary terms 术语表 词汇 vbd pbd xpbd pd incremental potential hessian" },
        { id: "a-2", title: "公式与符号速查", file: "chapters/appendix/a-2-cheatsheet.html",
          keywords: "cheatsheet 公式 符号 速查 G(x) f_i H_i omega 速查表 notation" },
        { id: "a-3", title: "参考文献 References", file: "chapters/appendix/a-3-references.html",
          keywords: "references papers arxiv 参考文献 论文 vbd pd xpbd liu chebyshev" },
        { id: "a-4", title: "Newton / Warp 术语表", file: "chapters/appendix/a-4-newton-glossary.html",
          keywords: "glossary 术语 newton warp kernel launch model state control coloring neo hookean avbd 词汇" },
        { id: "a-5", title: "TinyVBD ↔ Newton ↔ Isaac 对照速查", file: "chapters/appendix/a-5-mapping-cheatsheet.html",
          keywords: "mapping cheatsheet 对照 速查 tinyvbd newton isaac usd quaternion model state coloring 概念 映射" },
        { id: "a-6", title: "Newton / VBD / AVBD 参考文献", file: "chapters/appendix/a-6-newton-references.html",
          keywords: "references 参考文献 vbd avbd newton warp paper arxiv siggraph url 论文" },
        { id: "a-7", title: "IPC 参考文献", file: "chapters/appendix/a-7-ipc-references.html",
          keywords: "references 参考文献 ipc incremental potential contact li 2020 c-ipc convergent affine body dynamics abd barrier ccd siggraph url 论文" },
        { id: "a-8", title: "FEM / 连续介质 参考文献", file: "chapters/appendix/a-8-fem-references.html",
          keywords: "references 参考文献 fem 有限元 continuum 连续介质 deformation gradient neo-hookean stvk co-rotational smith 2018 sifakis 超弹性 论文" },
        { id: "a-9", title: "MPM 参考文献", file: "chapters/appendix/a-9-mpm-references.html",
          keywords: "references 参考文献 mpm material point sulsky apic jiang 2015 mls-mpm hu 2018 mpm lite pb-mpm ck-mpm siggraph arxiv url 论文" },
      ],
    },
  ],
};

/* 扁平化：供上下页导航与搜索使用 */
window.VBOOK.flat = (function () {
  const out = [];
  window.VBOOK.parts.forEach((p) => {
    p.sections.forEach((s) => out.push(Object.assign({ part: p.title, partLabel: p.label }, s)));
  });
  return out;
})();
